vslavik/poedit

src/logcapture.h
src/manager.cpp
src/prefsdlg.cpp
src/text_control.cpp

"Suppress" has two P's, even in British English.

Correct spelling of "suppress" and "suppressor"

---

src/text_control.cpp

This makes searching in multiline strings much easier.

Scroll search result into view

---

src/edframe.cpp
src/findframe.cpp
src/findframe.h

Before you freak out over the goto, look this code over carefully. The goto keyword is appropriate in this case because 1) we need to break out of a double loop and 2) it avoids redundant if statements.

Select the tab that contains the search result

---

src/language_impl_legacy.h

The "jw" language code was published in error.
It was withdrawn in favor of "jv" in 2001.
Source: http://www.loc.gov/standards/iso639-2/php/code_changes.php

Set language code for Javanese to "jv".

---

configure.ac

Add the required library explicitly, because with some toolchain updates they seems to be not resolved anymore
http://anonscm.debian.org/cgit/debian-l10n/poedit.git/commit/?id=bb2ead61b7759dc3038ee062eee27c9cce4f53f9

Add explicit boost dependencies in cpprest

---

src/icons.cpp

icons.cpp:62:66: warning: unused parameter ‘client’ [-Wunused-parameter]
bool ShouldBeMirorredInRTL(const wxArtID& id, const wxArtClient& client)

Silence compiler warning

---

src/wx_backports/wx_gtk_nativewin.cpp

gtk_widget_size_request has been deprecated since GtkWidget version 3.0.
Avoids compiler warnings like:
`wx_backports/wx_gtk_nativewin.cpp: In member function ‘bool xNativeWindow::Create(wxWindow*, wxWindowID, wxNativeWindowHandle)’:
wx_backports/wx_gtk_nativewin.cpp:64:5: warning: ‘void gtk_widget_size_request(GtkWidget*, GtkRequisition*)’ is deprecated: Use 'gtk_widget_get_preferred_size' instead [-Wdeprecated-declarations] gtk_widget_size_request(widget, &req);`

avoid deprecated gtk_widget_size_request()

---

configure.ac
src/json.h

configure.ac: check for system json.hpp if available, and use it

---

src/catalog.cpp
src/catalog.h
src/edapp.cpp
src/edapp.h
src/edframe.cpp
src/edframe.h

This adds support for the new command-line switch --go-to-line=<num>,
where <num> is the number of line in the .po file. This is related to
issue #356 on vslavik/poedit. It has been compiled with Visual Studio 2015 and tested on Windows.

Support for command-line switch --line

---

src/str_helpers.h
src/unicode_helpers.cpp

Fix compilation with ICU 59.1
Fixes #406
2.0.3 with this patch was binary tested on the distribution this was originally reported on: openSUSE Tumbleweed x86_64 20170729.
It's @vslavik's patch so I put him in as author.

Fix compilation with ICU 59.1

---

poedit.appdata.xml

This updates the appdata file to components version 0.11 - the one problem still in this version is the id field - running
appstreamcli validate poedit.appdata.xml
gives:
W - poedit.appdata.xml:poedit:4
The component ID is not a reverse domain-name. Please update the ID and that of 
the accompanying .desktop file to follow the latest version of the Desktop-Entry 
and AppStream specifications and avoid future issues.

Update appstream data to components version 0.11

---

.travis.yml

This patch enables ccache caching for a faster rebuild.
Without cache:
The build time increases about 90 seconds more than when ccache is not enabled(approx. 11m50s).
With existing cache([log](https://travis-ci.com/Lin-Buo-Ren/poedit/jobs/128351224)):
the build time dropped to about 7 minutes.
The build results in a 35.38MiB of cache data, it *might* be sane to further restrict ccache size to 50MiB to avoid constantly increasing cache size in subsequent builds(by default the cache size limit is 5.0GiB)
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

Travis: Incorporate Compiler cache(ccache)

---

snap/snapcraft.yaml

There's a poorly documented plug assertion format that applies to the
entire snap, by migrating to this we can avoid duplicating the plug
enumeration for each of the _app_name_ and also compatible with plugs
that has attributes (like the content interface).

Use global scope plugs assertion in the snap

---

snap/snapcraft.yaml

The fix is already merged upstream thus no longer to be workarounded.
Prepend $SNAP/share to XDG_DATA_DIRS · ubuntu/snapcraft-desktop-helpers
https://github.com/ubuntu/snapcraft-desktop-helpers/pull/121

Drop XDG_DATA_DIRS workaround from snap build

---

snap/snapcraft.yaml

Snapcraft already gives `$SNAPCRAFT_STAGE/bin` priority in the build
step and doesn't require setting it manually.

Drop unnecessary PATH modification in snap build

---

admin/ax_boost_base.m4
admin/ax_cxx_compile_stdcxx.m4

Update macros used to upstream’s v2019.01.06 release.
- Fixes build issue of Poedit on powerpc64 and powerpc64le archs
on some Linux distros. See upstream commit:
https://github.com/autoconf-archive/autoconf-archive/commit/4b3c263

Update autoconf-archive macros

---

snap/snapcraft.yaml

No reason to split share content into multiple entries (and accidentally omit some), just package the entire `share/` directory.
Motivation: b3b28e047b4ceb18943fca6ea6ba97b305fccb76, similarly appdata files are accidentally not packages (but probably not useful).
@Lin-Buo-Ren can you see any problem with this simplification, i.e. could it possibly pull in some junk from other parts? TIA!

Snapcraft: simplify $prefix/share files packaging

---

Makefile.am

The default directory for the appdata xml file changed from appdata to metainfo, as can be seen in https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
> Upstream projects can ship one or more metainfo files in /usr/share/metainfo/%{id}.metainfo.xml, where id is a unique identifier of this specific component.
> ...
> AppStream tools scan the /usr/share/appdata/ path for legacy compatibility as well. It should not be used anymore by new software though, ...
This commit changes the data installation directory in the from `share/appdata` to `share/metainfo`.
p.s.: I didn't change the filename replacing `...appdata.xml` -> `...metainfo.xml` as I notice almost all apps installed in my system didn't change it. Let me know if you want me to change …

Change dir for the appdata.xml to metainfo

---

Makefile.am
configure.ac
src/json.h

Patch configure file to find the new json.hpp file location

Update JSON for Modern C++ to version 3

---

src/welcomescreen.cpp

Fixes
welcomescreen.cpp: In constructor 'EmptyPOScreenPanel::EmptyPOScreenPanel(PoeditFrame*)':
welcomescreen.cpp:289:26: error: 'LearnMoreLink' does not name a type; did you mean 'learnMore'?
auto learnMore = new LearnMoreLink(this, "http://www.gnu.org/software/gettext/manual/html_node/", _("(Learn more about GNU gettext)"));
^~~~~~~~~~~~~
learnMore

Add header for LearnMoreLink.

---

src/catalog.cpp
src/catalog.h
src/crowdin_gui.cpp
src/crowdin_gui.h
src/edframe.cpp

Addresses #638, #641 discussions:
1. Files fetched from Crowdin in-app, or fetched previously and now opened from recent files, are synced when saved
2. The explicit Sync button always saves first, avoiding double-upload and any funny asynchronous business

Crowdin v2 saving consistency

---

src/concurrency.h

Fix ' concurrency.h:606:10: error: ‘atomic_bool’ in namespace ‘std’ does not name a type; did you mean ‘atomic_load’? ' build error.

Add missing include

---

src/customcontrols.cpp
src/customcontrols.h

Fixes the following issue:
If you have a comment containing an ampersand (&) in the comment
sidebar, it would be treated as an accelerator, i.e. the ampersand
would not be shown, and the character after it would be underlined
(on Windows), or not (on Mac).

Escape '&' in the comment sidebar

---

.gitmodules

Unencrypted git:// protocol is no longer supported and errors out when trying to pull `letsmove`, `LucenePlusPlus` and `zlib` submodules
More info here: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Change git URLs to HTTPS in submodules

---

artwork/Makefile.am

Upon installation, updating icon cache is relevant so that new icons can be found by the system.
Upon a [staged installation](https://www.gnu.org/software/automake/manual/html_node/Staged-Installs.html) though, i.e. when `DESTDIR` is set to a staging installation area, it is not relevant to update the icon cache as this cache is not the actual target system's cache.
Staged installation is typically used when creating a package of the application. Cache update is a problem well known to packagers which typically handle it by wrapping cache update commands into scripts to be executed at post (un)installation time - on the real target system.
See also:
- #703
- [The tutorial](https://ptomato.name/advanced-gtk-techniques/html/desktop-file.html) referenced in the ticket which actually mentions …

Do not install icon cache upon staged install

---

src/edlistctrl.cpp
src/edlistctrl.h

This is a naive attempt to fix the sizing issues of the ID column observed with wxGTK and reported in #643 and #714.
Basically:
- Sizing computation is delayed, so we can't fix the width immediately until we're sure it has been computed
- Despite being fixed, last column automatically grows and `wxDataViewColumn::GetWidth()` returns the actual width, not the fixed width, so we need a way to memorize the fixed width ourselves. I've created a custom `wxDataViewColumn` for that, I'm not sure it's the best approach though
I've tested this with the following environment:
- wxGTK version: 3.1.6
- GTK+ version: 3.24.33
- Operating system: openSUSE Tumbleweed (20220414)

Fix sizing of the ID column on wxGTK

---

src/recent_files.cpp

Recent file icon loading may fail e.g. because of missing read
permission or other packaging issue.
Icon rescale code introduced by 5fc8d6c did not foresee this
possibility.
Add a condition to prevent it from manipulating a non-ok icon.
This prevents assertion error although icon loading failure will still
lead to an error message showed to user.
See #758.

Do not try to rescale recent file icon when it cannot be loaded

---

src/extractors/extractor.cpp

Fixes the issue for cases when you are trying to update from source code and one of the files is a link to non-existing, which led to Permission denied exception.

Skip files that do not exist

---

src/utility.cpp

On Linux, `TempOutputFileFor::ReplaceFile` returns a wrong status, indicating the replacement has failed when it has not. This leads to a misleading error message displayed to user on every po file save.
The cause is in the verification of the return codes of `chown`/`chmod`. `chown` and `chmod` return a non-zero integer value when an error occurs. A non-zero value is considered as a boolean `true`.
This commit fixes the logic error; It explicitly compares the returned integer value to another integer to avoid confusion.

Fix chmod/chown return code verification logic

---

deps/gettext/gettext-macos-catalina-dont-touch-parent-dirs.patch
deps/gettext/gettext-smaller-build.patch

Fixes build failure on macOS 13 whose patch program does not apply fuzzy patches.
Fixes #781

Regenerate patch files for gettext 0.21.1

---

src/custom_buttons.cpp
src/custom_buttons.h

Fixes #693 
There is no reliable way for screen reader users to find out the fuzzy (needs work) status. After some research, the most likely cause is as follows:
1. SwitchButton is owner drawn and therefore sets the BS_OWNERDRAW window style
2. When BS_OWNERDRAW is set, all other window styles should be ignored [according to the docs](BS_OWNERDRAW)
3. The default MSAA implementation in Windows ignores other window styles. As it relies on window style to find out whether the button is either a push button or a check box, this information is lost, and MSAA treats the toggle as a plain button without checkable state.
Implement a wxAccessible subclass as outlined in #696 
Executed from source, ensured that the needs work button is reported as check box and that toggling the button is properly …

Add accessibility support to SwitchButton on Windows

---

Poedit.vcxproj
Poedit.vcxproj.filters
Poedit.xcodeproj/project.pbxproj
src/Makefile.am
src/attentionbar.cpp
src/customcontrols.cpp
src/customcontrols.h
src/edframe.cpp
src/editing_area.cpp
src/prefsdlg.cpp
src/propertiesdlg.cpp
src/recent_files.cpp
src/sidebar.cpp
src/static_ids.h
src/welcomescreen.cpp

This reorganizes Poedit's code to be able to a) assign static IDs safely and b) add more quickly if the need arrises.
See the relevant NVDA plugin's code here: https://github.com/nvaccess/nvda/blob/master/source/appModules/poedit.py
@LeonarddeR I'd appreciate your review if you could spare the time. Most of the changes are internal to Poedit and of little interest, the interesting bit is the `static_id.h` file:
1. Is it understandable?
2. Does it cover NVDA's needs?
3. Can it be improved and/or is there more that you guys need?
I *think* it covers it (`PRO_IDENTIFIER` and `MAIN_SPLITTER_IDENTIFIER` seem to be needed just for the clever/hacky workaround for lack of static IDs), but I'm far from being 100% sure.

Use static IDs for controls needed by NVDA

---

net.poedit.Poedit.appdata.xml

Fixes the following warnings and info when running the `appstreamcli validate` command on Linux:
- W: screenshot-default-missing
- I: content-rating-missing
- I: developer-info-missing
"I: developer-name-tag-deprecated", which tells use of the `developer_name` tag that was deprecated in AppStream 1.0.0, is not fixed for now because some software centers may not support AppStream 1.0.0 yet.
Originally taken from [the patch on Flathub](https://github.com/flathub/net.poedit.Poedit/blob/b6d901fd89ef09545bbfa74e908dc8419c512fd3/appdata.patch).
---
FYI the current result of the command:
```
ryo@b760m ~/work/tmp/poedit (master =)]$ appstreamcli validate net.poedit.Poedit.appdata.xml
W: net.poedit.Poedit:16: screenshot-default-missing
I: net.poedit.Poedit:40: developer-name-tag-deprecated
I: …
```

Fix appstreamcli validate warnings and info

---

configure.ac

The recently released Boost 1.89.0 removed the compatibility stub, so requiring the BOOST_SYSTEM library will now lead to a build failure. This commit also bumps the minimum version of Boost to 1.69.0, as that was the first version where this is headers only.

Boost.System has been headers only since 1.69.0
